apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app-frontend.fullname" . }}
  labels:
    {{- include "todo-app-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: http
  selector:
    {{- include "todo-app-frontend.selectorLabels" . | nindent 4 }}
