apiVersion: apps/v1
kind: Deployment
metadata:
  name: helidon-examples-todo-cassandra
  labels:
    app.kubernetes.io/name: helidon-examples-todo-cassandra
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: helidon-examples-todo-cassandra
  template:
    metadata:
      labels:
        app.kubernetes.io/name: helidon-examples-todo-cassandra
    spec:
      containers:
        - name: todo-cassandra-container
          image: ammbra/helidon-examples-todo-cassandra
          imagePullPolicy: Always
          ports:
            - containerPort: 9042
              name: http-dev
