kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "todo-app-backend.fullname" . }}
data:
  env: {{ .Values.configmap.env }}
  services: |-
    zipkin.host: {{ .Values.configmap.zipkin }}
  cassandra: |-
    servers:
      - host: {{ .Values.configmap.cassandra.host }}
        port: {{ .Values.configmap.cassandra.port }}