apiVersion: v1
kind: Service
metadata:
  name: {{  .Values.global.service.name }}
  labels:
    {{- include "todo-app-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: http
  selector:
    {{- include "todo-app-backend.selectorLabels" . | nindent 4 }}
